- name: APP DATABASE Create service acccount for this application
  user: name={{ userweb }} shell=/usr/sbin/nologin createhome=yes

- name: APP DATABASE Create database owner as an OS         user
  user: name={{ userdba }} createhome=yes shell=/bin/bash

- name: APP DATABASE Create database owner as a  postgresql role
  postgresql_user: name="{{ userdba }}" password="{{ userdba_password }}" role_attr_flags=NOCREATEROLE,NOSUPERUSER login_host="/var/run/postgresql" login_unix_socket="/var/run/postgresql/11-main.pid" login_user=postgres
  become: yes
  become_user: postgres
  become_method: sudo

- name: APP DATABASE Create database user  as a  postgresql role
  postgresql_user: name={{ userweb }} role_attr_flags=NOCREATEROLE,NOSUPERUSER login_host="/var/run/postgresql" login_unix_socket="/var/run/postgresql/11-main.pid" login_user=postgres
  become: yes
  become_user: postgres
  become_method: sudo

- name: APP DATABASE Create database {{ db }}
  postgresql_db: name={{ db }} owner={{ userdba }} encoding='UTF-8' template='template0' login_host="/var/run/postgresql" login_unix_socket="/var/run/postgresql/11-main.pid" login_user=postgres
  become: yes
  become_user: postgres
  become_method: sudo

- name: APP DATABASE Allow peer connection for database owner {{ userdba }}
  lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf state=present
              line=" local   {{ db }}             {{ userdba }}                                 peer"


- name: APP DATABASE Allow peer connection for database user  {{ userweb }}
  lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf state=present
              line=" local   {{ db }}             {{ userweb }}                                 peer"

- name: APP DATABASE GRANT MDL privileges to {{ userweb }}
  postgresql_privs: db="{{ db }}" state=present privs=SELECT,INSERT,UPDATE,DELETE type=default_privs objs=TABLES role="{{ userweb }}" login_host="/var/run/postgresql" login_unix_socket="/var/run/postgresql/11-main.pid" login_user={{ userdba }}
  become: yes
  become_user: "{{ userdba }}"
  become_method: sudo

- name: APP add www-data to the {{ userweb }} group
  user: name=www-data groups={{ userweb }}